version: '3.5'

services:
  lumen:
    ports:
      - "8000:8000"

    build: .
    restart: always
    network:
     - lumen-network
     - mysql
    volumes:
      - lumen-test-volume:/var/www/html/


volumes:
   lumen-test-volume:
    name: lumen-test-volume
networks:

  lumen-network:
    driver: bridge
