version: '3.5'


services:
  lumen:
    image: gabrielsoaresdev/lumen-test:latest
    restart: always
    env_file:
      - stack.env
    ports:
    - "8000:8000"
    networks:
      - lumen-base-network


  # nginx-lumen:
  #  container_name: nginx-lumen
  #  image: nginx:1.17.6-alpine

  #  restart: always
  #  depends_on:
  #  - lumen
  #  ports:
  #   - "80:80"
  #  volumes:
  #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf


networks:
 lumen-base-network:
    name: lumen-base-network
    driver: bridge






