version: '3.5'

services:
  lumen:
    ports:
      - "8000:8000"
    image: gabrielsoaresdev/lumen-test:latest
    restart: always
    env_file:
      - stack.env


networks:
  default:
    name: mysql-network
    external: true

