version: '3.5'

services:
  lumen:
    ports:
      - "8000:8000"

    build: .
    restart: always
    network:
     - lumen-network
     - mysql
    volumes:
      - .:/var/www/html/

networks:

  lumen-network:
    driver: bridge
