version: '3.5'

services:
  lumen:
    container_name: lumen
    ports:
     - "8000:8000"
    build: .
    restart: always
    volumes:
      - ".:/var/www/html/"

    networks:
     - lumen-network
    depends_on:
     - mysql

  mysql:
     container_name: lumen-mysql
     image: mysql:8.0
     restart: always
     volumes:
       - mysql-local:/var/lib/mysql:rw
     environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
     ports:
     - "3305:3306"

     networks:
      - lumen-network

volumes:
 mysql-local:
  name: mysql-local
networks:
  lumen-network:
    driver: bridge


