version: '3.5'

services:
  lumen:
    ports:
      - "8000:8000"

    build: .
    command: php -S lumen:8000 -t public
    restart: always
    depends_on:
      - mysql
  mysql:
   image: mysql:8.0
   restart: always

   environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
   ports:
      - "3305:3306"
   command: mysqld --default-authentication-plugin=mysql_native_password
   volumes:
      - ./docker/mysql-data:/var/lib/mysql:rw
