version: '3.5'

services:
  lumen:
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    networks:
      - lumen-test

    command: php -S lumen:8000 -t public
    restart: always

networks:
  mysql:
    driver:
     bridge
  lumen-test:
     name: lumen-test
