version: '3.1'

services:
  lumen:
    networks:
      - mysql-network
    ports:
      - "8000:8000"
    image: gabrielsoaresdev/lumen-test:latest
    restart: always


volumes:
   lumen-test-volume:
    name: lumen-test-volume
