version: '3'


networks:
  laravel:
    
services:
   nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
        - "7000:80"
      volumes:
       - .:/var/www/html
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - mysql
      networks:
        - laravel


   mysql:
      image: mysql:5.7
      container_name: mysql
      ports:
        - "3306:3306"
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: root
        MYSQL_USER: root
        MYSQL_PASSWORD: password
      networks:
        - laravel
   php:
      build:
       context: .
       dockerfile: Dockerfile
      container_name: php
      volumes:
        - .:/var/www/html
      ports:
        - "9000:9000"
      networks:
        - laravel
   composer:
      image: composer:latest
      container_name: composer
      volumes:
        - .:/var/www/html
      working_dir: /var/www/html
      depends_on:
        - mysql
      entrypoint: ['composer','install']
      networks:
        - laravel
  
   artisan:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: artisan
      volumes:
        - .:/var/www/html
      working_dir: /var/www/html
      depends_on:
        - php
      entrypoint: ['php','/var/www/html/artisan']
      networks:
        - laravel



    

