version: '3.5'


services:
  api-tasks:
    container_name: api-tasks
    build: .
    ports:
     - "8005:8005"
    restart: always
    volumes:
      - ".:/var/www/html/api-tasks"
      - vendor-api-tasks:/var/www/html/api-tasks/vendor
    networks:
    - api-tasks-network
    - mysql-network
    - rabbitmq-network
volumes:
 vendor-api-tasks:
  name: vendor-api-tasks

networks:
  api-tasks-network:
   name: api-tasks-network
   driver: bridge

   name: mysql-network
   external: true








