version: '3.5'


services:
  lumen:
    image: gabrielsoaresdev/lumen-test:latest
    container_name: lumen-base
    restart: always
    env_file:
      - stack.env
    ports:
    - "8000:8000"
    networks:
      - lumen-base-network




networks:
 lumen-base-network:
    name: lumen-base-network
    driver: bridge








