name: DEPLOY - PROD
on:
 workflow_dispatch:
 push:
  branches:
      - main
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Deploy para prod
        uses: fjogeleit/http-request-action@v1
        with:
         url: 'https://181.215.135.140:9443/api/stacks/webhooks/8efac57f-d8d6-457c-9929-41aaf3bdac84'
         method: 'POST'
         customHeaders: '{"Content-Type": "application/json"}'
         timeout: 60000



