name: DEPLOY - PROD
on:
 workflow_dispatch:
 push:
  branches:
      - master
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          # Contexto onde está o arquivo Dockerfile, normalmente é .
          context: ./
          file: Dockerfile
          tags: lumen
          no-cache: true
          push: true

      - name: Deploy para o host
        uses: easingthemes/ssh-deploy@main

        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOUCER: "/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{secrets.REMOTE_TARGET}}
      # - name: Check running containers
      #   run: docker ps
      # - name: Start containers
      #   run: docker-compose -f "docker-compose-prod.yml" up -d --build
