name: DEPLOY - PROD
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          # Contexto onde está o arquivo Dockerfile, normalmente é .
          context: .
          file: Dockerfile
          # Qual a tag
          tags: gabrielsoaresdev/lumen-test:latest
          no-cache: true
          push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Rebuild  stack
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://181.215.135.140:9443/api/stacks/webhooks/2f8bcfc2-4ec5-4ebc-b16d-a369af93f29b'
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          timeout: 60000

