name: DEPLOY - PROD
on:
 workflow_dispatch:
 push:
  branches:
      - master
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Deploy para o host
        uses: easingthemes/ssh-deploy@main

        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOUCER: "/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{secrets.REMOTE_TARGET}}
