name: MERGE - MAIN
on:
 workflow_dispatch:
 push:
        branches:
         - development
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@master
       - name: Merge development -> master
         uses: devmasx/merge-branch@master
         with:
          type: now
          from_branch: development
          target_branch: main
          github_token: ${{ secrets.TOKEN_ACTION_GIT }}
